# Generated by Django 4.2 on 2023-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('registrationDate', models.DateField(verbose_name='Registration Date')),
            ],
        ),
    ]
