# Generated by Django 4.2 on 2023-04-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertool', '0002_alter_userbase_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
    ]
