# Generated by Django 4.2 on 2023-04-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertool', '0003_alter_userbase_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='registrationDate',
        ),
    ]
